### ISSUE TITLE
WebRTC Not Working

### ISSUE THREAD

**Issue by wpmanoj** [cefsharp/CefSharp#2525]
My issue is - WebRTC not Working with version 49.0.1 (WinForms). Same Source i using work with version 63. i'm Struggling with Windows Platform issue so i can't update than 49.

dev tool gave me this as error not -
Uncaught TypeError: navigator.mediaDevices.getUserMedia is not a function

using Nuget. 

my Code is - 
```
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
window.URL = window.URL || window.webkitURL || window.msURL || window.mozURL;

if(navigator.mediaDevices){
    navigator.mediaDevices.getUserMedia({
        video: {
            width : 600,
            height : <?php echo $control['pmi_size']['height']; ?>
        }
    }).then(gumSuccess).catch(fail);
} else if(navigator.getUserMedia){
    navigator.getUserMedia({
        video: true
    }, gumSuccess, fail);
} else {
    fail();
}
```

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

**Comment by wpmanoj** [comment]
I'm Sorry Amaitland, This is an issue. because i followed every step mentioned to active webrtc. Works for newer too. but not for 49. 
i think this will be helpful for every one. beacause lot of discussion here about this version. we just need to know is what are the changes we should do with this version (49) to activate webrtc to access web cam.

**Comment by amaitland** [comment]
> Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer -pre release and test with that also).

As per https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Version `49` is over 2 years old and is no longer supported. I don't have the time or resources to support multiple versions, specially not ones that old. 

> Should work with win 7 ultimate too. so i can't update than 49.

This is incorrect, version `67` will run on `Windows 7`. `CefSharp` will run on every windows platform that `Chromium` supports.

This issue tracker is not a support forum, if you have a question ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp)
